### ISSUE TITLE
the tracking performance is not as good as report in paper

### ISSUE THREAD

**Issue by chenrxi** [fatemeh-slh/ArTIST#3]

**Comment by chenrxi** [comment]
especially for the first five frames, How do you solve it?

**Comment by chenrxi** [comment]
cannot re-create the paper's result using private detections @fatemeh-slh . Please give me some advice. The IDSW is higher than the paper reported

**Comment by chenrxi** [comment]
Please

**Comment by chenrxi** [comment]
![image](https://user-images.githubusercontent.com/60959000/127169491-7ef4f3d4-2434-48ec-9a8e-b722aaee47ec.png)
![image](https://user-images.githubusercontent.com/60959000/127169875-7d5c3c89-6b46-4735-9af6-4e41c09de94f.png)

it(the right person who is occluded) predicts the wrong direction for its future trajectory.  Almost for 40 n_sampling.
How can I solve it? Can you help me?

**Comment by fatemeh-slh** [comment]
Regarding your questions, please follow these explanations:

1- Note that in online tracking, we do not generate the future of an occluded bbox. The aim is to 1) find the likelihood of assigning each detection to a tracklet that has been fully observed so far, same as what we have shown in `demo_scoring.py` and 2) when there is no assignment for a tracklet, we keep that tracklet alive (tentatively alive) and at each time step we do inpainting for the time gap and if there is a detection in the scene that has a high overlap to the last inpainted bbox, we use the likelihood as the score in the cost matrix and if the assignment happens (as the result of applying Munkres) for these tentatively alive tracklets, we update their history with the inpainted bboxes. So, for a tentatively alive tracklet, we keep them for 30 frames, and if there is no matching detection for such tracklets, we don’t consider the inpainted trajectory and just assign a very low score for them so that the Munkres algorithm does not assign any detection to those tracklets. If there is no assignment to a tracklet for 30 frames we remove that from the list of tracklets.

2- To select one of these S candidates, we use a tracklet rejection scheme (TRS), as follows: if there is a candidate to be selected, we compute the intersection over union (IoU) of the last generated bounding box with all the detections in the scene. The model then selects the candidate with the highest IoU, if it surpasses a threshold. However, in some cases, the last generated bounding box of one of the candidates may overlap with a false detection or detection for another object, i.e., belonging to a different tracklet. To account for these ambiguities, we continue predicting boxes for all candidates for another 1–2 frames and compute the IoUs for these frames as well. We then select the candidate with the maximum sum of IoUs. Please note that, for tracklet rejection in the case of inpainting, we use an IOU threshold of 0.5 and set t_TRS = 1 for low frame-rate videos and t_TRS = 2 for high frame-rate ones. 
For more details about the tracking algorithm, please see the supplementary material (page 13 of (https://arxiv.org/pdf/2012.02337.pdf)).


3- This repository contains only the ArTIST motion model (and not the tracking pipeline). The tracking code may be released in another repo in the future. However, you can find the implementation details in the paper and in the released demos which are sufficient to be utilized in any tracking pipeline. If you want to compare or use the output of our tracker please check the MOTchallenge leaderboard.

**Comment by chenrxi** [comment]
Thanks for your reply.
1. According to your explanation, you only update the history trajectory if the last bounding box overlaps with the detections with the IOU for more than 0.5 in the scene. SO, you do not inpaint the bounding box offline instand of online?
![image](https://user-images.githubusercontent.com/60959000/127257138-8576d095-69c6-40f7-9f89-69afb17f9948.png)
2. But so far, the generated trajectory is inaccurate after being occluded for 5-6 frames. They move in the opposite directions in the following picture. I wonder whether it is my fault or the drawback of the ArTIST motion model.
![image](https://user-images.githubusercontent.com/60959000/127257373-fc88ed1f-f779-4334-bc73-b05bf384cf04.png)
The red is last generated bounding box(sampled_detection in the demo), the blue plot the generated trajectory(sampled_boxes in the demo) the green plot is the observed trajectory(from gt bbox)
Next time would you please not close the issue so quickly and we can discuss more. Thank you.
the MOTchallenge leaderboard do not provide private detection tracking result

**Comment by chenrxi** [comment]
@fatemeh-slh .sorry, the inpainting result is really bad.

**Comment by chenrxi** [comment]
![558_38](https://user-images.githubusercontent.com/60959000/128197347-de21e78f-9734-465a-a45d-2e42e993aafd.jpg)
![500_38](https://user-images.githubusercontent.com/60959000/128197418-35b6c685-9638-43f6-a72c-1cee98cb6568.jpg)
![598_74](https://user-images.githubusercontent.com/60959000/128197448-d4d16a46-fb5f-44b4-add9-dfeb9e5feceb.jpg)
the result of the motion model is not good, Here are some phenomenon，the gt bbox is in green, the sampled detection is in red. Could you give me some advice, Thank you.

**Comment by UsersNGT** [comment]
where the TRS implement in this  repository ? Could you tell me ?  Thank you.

**Comment by chenrxi** [comment]
> where the TRS implement in this repository ? Could you tell me ? Thank you.

Have you re-implemented the paper result?
